#!/bin/bash

case $2 in

"usage")
  echo 
  echo "todo.sh $(basename $0) [ITEM_NUMBER]"
  echo
  echo "  Prompts user to edit the todo entry with #ITEM_NUMBER." 
  echo "  If ITEM_NUMBER isn't specified, opens \$TODO_DIR/todo.txt in \$EDITOR."
  echo
  ;;

"help")
  echo         
  echo "todo.sh $(basename $0) [ITEM_NUMBER]"   
  echo
  echo "  Prompts user to edit the todo entry with #ITEM_NUMBER."   
  echo "  If ITEM_NUMBER isn't specified, opens \$TODO_DIR/todo.txt in \$EDITOR."       
  echo
  ;;

*)
  if [[ -z $2 ]]; then
    FILE=$TODO_FILE
    if [ -n "$EDITOR" ]; then 
      $EDITOR "$FILE" 
    else 
      echo "Error: The EDITOR environment variable is not set"
    fi
  else
    FILE=$TODO_DIR/$2.txt
    entry="$(todo.sh list | grep ^$2\\s | sed "s/$2//")" 
    printf "Current entry: $entry\n"
    read -p 'Updated entry:  ' newval
    todo.sh replace $2 $newval
  fi
  ;;
esac


